export const FETCH_PET_IMG = "FETCH_PET_IMG";
export const FETCH_PET_IMG_PENDING = "FETCH_IMG_PENDING";
export const FETCH_PET_IMG_SUCCESS = "FETCH_IMG_SUCCESS";
export const FETCH_PET_IMG_ERROR = "FETCH_IMG_ERROR";
